services:
  # -------------------------------------
  # PostgreSQL
  # -------------------------------------
  postgres:
    image: postgres:17
    container_name: psql_source
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  # -------------------------------------
  # Postgres Migrations
  # -------------------------------------
  flyway-postgres:
    image: flyway/flyway
    container_name: postgres_migrations
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    command: -url=jdbc:postgresql://postgres:5432/postgres -user=postgres -locations=filesystem:/flyway/postgres migrate
    volumes:
      - ./migrations/postgres:/flyway/postgres
    environment:
      FLYWAY_CONNECT_RETRIES: 10

  # -------------------------------------
  # ClickHouse
  # -------------------------------------
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: ch_analytics
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=12345
    healthcheck:
      test: [ "CMD", "clickhouse-client", "--query", "SELECT 1" ]
      interval: 5s
      retries: 5

  clickhouse-migrations:
    image: pipeline_kpi_etc
    depends_on:
      clickhouse:
        condition: service_healthy
    volumes:
      - ./migrations/clickhouse:/app/migrations/clickhouse
    environment:
      CH_HOST: "clickhouse"
    entrypoint: [ "scripts/ch_migrations.sh" ]

  tabix:
    image: spoonest/clickhouse-tabix-web-client:latest
    ports:
      - "6060:80"
    depends_on:
      clickhouse:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - CH_NAME=clickhouse
      - CH_HOST=http://localhost:8123
      - CH_LOGIN=default
      - CH_PASSWORD=12345

  kpi-service:
    image: pipeline_kpi_etc
    depends_on:
      clickhouse:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./migrations/clickhouse:/app/migrations/clickhouse
    environment:
      CH_HOST: "clickhouse"
      CH_URL: "jdbc:ch://clickhouse:8123/default?user=default&password=12345"


  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    volumes:
      - ./drivers:/opt/spark/jars:ro
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    ports:
      - "8080:8080"  # Spark Web UI
      - "7077:7077"  # Spark Master port
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/8080'"]
      interval: 10s
      timeout: 5s
      retries: 5

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    volumes:
      - ./drivers:/opt/spark/jars:ro
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8081:8081"  # Spark Worker UI

# prefecthq/prefect:3.3-python3.11

  prefect-server:
    image: prefecthq/prefect:3.3-python3.11
    container_name: prefect-server
    command: prefect server start --host 0.0.0.0
    environment:
      - PREFECT_API_URL=http://localhost:4200/api
    ports:
      - "4200:4200"
    depends_on:
      - postgres
    healthcheck:
      test:  ["CMD-SHELL", "bash -c '</dev/tcp/localhost/4200'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  prefect-worker:
    image: prefecthq/prefect:3.3-python3.11
    container_name: prefect-worker
    depends_on:
      prefect-server:
        condition: service_healthy
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    command: prefect worker start --pool default-agent-pool

  workflow:
    image: pipeline_kpi_etc
    depends_on:
      prefect-server:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      postgres:
        condition: service_healthy
      spark-master:
        condition: service_healthy
    environment:
      PG_URL: "jdbc:postgresql://postgres:5432/postgres?user=postgres&password=postgres"
      CH_URL: "jdbc:ch://clickhouse:8123/default?user=default&password=12345"
      SPARK_MASTER_URL: "spark://spark-master:7077"
      PREFECT_API_URL: "http://prefect-server:4200/api"
    command: python src/workflow.py

volumes:
  postgres_data:
  clickhouse_data:

