services:
  # -------------------------------------
  # PostgreSQL
  # -------------------------------------
  postgres:
    image: postgres:17
    container_name: psql_source
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  # -------------------------------------
  # Postgres Migrations
  # -------------------------------------
  flyway-postgres:
    image: flyway/flyway
    container_name: postgres_migrations
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    command: -url=jdbc:postgresql://postgres:5432/postgres -user=postgres -locations=filesystem:/flyway/postgres migrate
    volumes:
      - ./migrations/postgres:/flyway/postgres
    environment:
      FLYWAY_CONNECT_RETRIES: 10

  # -------------------------------------
  # ClickHouse
  # -------------------------------------
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: ch_analytics
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=12345
    healthcheck:
      test: [ "CMD", "clickhouse-client", "--query", "SELECT 1" ]
      interval: 5s
      retries: 5

  # -------------------------------------
  # ClickHouse  Migrations
  # -------------------------------------
#  flyway-clickhouse:
#    image: flyway/flyway:latest
#    container_name: clickhouse_migrations
#    depends_on:
#      - clickhouse
#    volumes:
#      - ./migrations/clickhouse:/flyway/sql
#      - ./drivers:/flyway/drivers
#    entrypoint: >
#      sh -c "flyway -url=jdbc:clickhouse://clickhouse:8123/default -user=default -password=12345 -locations=filesystem:/flyway/sql -driver=com.clickhouse.jdbc.ClickHouseDriver migrate"

#  clickhouse-migrations:
#    image: shini4i/clickhouse-migrations
#    container_name: ch-migrations
#    volumes:
#      - ./migrations/clickhouse:/migrations
#      - ./migrations/clickhouse-migrations.yml:/app/clickhouse-migrations.yml
#    depends_on:
#      - clickhouse
#    entrypoint: [ "clickhouse-migrations", "migrate" ]

  tabix:
    image: spoonest/clickhouse-tabix-web-client:latest
    container_name: tabix
    ports:
      - "6060:80"
    depends_on:
      - clickhouse
    restart: unless-stopped
    environment:
      - CH_NAME=clickhouse
      - CH_HOST=http://localhost:8123
      - CH_LOGIN=default
      - CH_PASSWORD=12345

volumes:
  postgres_data:
  clickhouse_data:
